import Foundation
import MLSCodec
import MLSCrypto
import MLSFraming
import MLSVectorSupport
import Testing

@testable import MLSProfileRFC9420

/// Every top-level RFC 9420 wire structure, decoded then re-encoded and
/// checked byte-identical to the vector — the strongest static signal this
/// phase has, since it's essentially one record per structure this phase
/// ships. Per the vector's own spec (test-vectors.md, "Messages"): "The
/// contents of each field must decode using the corresponding structure.
/// Each decoded object must re-encode to produce the bytes in the test
/// vector." No semantic/cryptographic checks — this is a pure structural
/// round-trip, unlike message-protection.json.
///
/// The seven proposal fields are the proposal *bodies* (e.g. `Add`'s
/// `key_package`), not the tagged `Proposal` enum — RFC 9420 wraps each body
/// in a single-field struct (`struct { KeyPackage key_package; } Add;`),
/// which is wire-identical to the bare field since a one-field struct has no
/// extra framing in TLS presentation language. So each is decoded here as
/// the same inner type `Proposal`'s corresponding case already holds.
@Suite("messages.json (mlswg/mls-implementations, official)")
struct MessagesTests {
	static let records = try! VectorFile.load("messages", as: [MessagesVector].self)

	private func roundTrip<T: MLSCodable>(_ type: T.Type, _ data: Data) throws {
		var reader = MLS.Reader(data)
		let value = try T(from: &reader)
		try reader.finish()
		#expect(try value.mlsEncoded() == data)
	}

	@Test("every field decodes and re-encodes byte-identically", arguments: records)
	func structural(_ record: MessagesVector) throws {
		try roundTrip(MLS.RFC9420.Message.self, record.mlsWelcome.bytes)
		try roundTrip(MLS.RFC9420.Message.self, record.mlsGroupInfo.bytes)
		try roundTrip(MLS.RFC9420.Message.self, record.mlsKeyPackage.bytes)
		try roundTrip(MLS.RFC9420.Message.self, record.publicMessageApplication.bytes)
		try roundTrip(MLS.RFC9420.Message.self, record.publicMessageProposal.bytes)
		try roundTrip(MLS.RFC9420.Message.self, record.publicMessageCommit.bytes)
		try roundTrip(MLS.RFC9420.Message.self, record.privateMessage.bytes)

		try roundTrip(MLS.RFC9420.GroupSecrets.self, record.groupSecrets.bytes)
		try roundTrip(MLS.RFC9420.Commit.self, record.commit.bytes)

		// The seven proposal bodies — bare inner types, not the tagged `Proposal` enum.
		try roundTrip(MLS.RFC9420.KeyPackage.self, record.addProposal.bytes)
		try roundTrip(MLS.RFC9420.LeafNode.self, record.updateProposal.bytes)

		// `remove_proposal` is a bare `LeafIndex`, generated by the official
		// suite without going through the bounds-checked type — some records
		// legitimately carry a value at/above `LeafIndex.ceiling` (2^24).
		// mls-rs's own vector consumer (serialization.rs) hits the same
		// decode error and, for exactly this field, falls back to a raw
		// `u32` decode to confirm the value really is out of range rather
		// than treating it as a bug; mirrored here rather than loosening the
		// type's real invariant.
		do {
			try roundTrip(MLS.LeafIndex.self, record.removeProposal.bytes)
		} catch MLS.TreeMathError.leafIndexTooLarge(let value) {
			#expect(value >= MLS.LeafIndex.ceiling)
		}

		try roundTrip(
			MLS.RFC9420.PreSharedKeyIdentifier.self, record.preSharedKeyProposal.bytes)
		try roundTrip(MLS.RFC9420.ReInitProposal.self, record.reInitProposal.bytes)
		try roundTrip(
			MLS.RFC9420.ExternalInitProposal.self, record.externalInitProposal.bytes)

		// `Extension extensions<V>;` and `optional<Node> ratchet_tree<V>;` are
		// bare vectors, not wrapped in a named struct — round-tripped directly
		// via decodeVector/encodeVector rather than a one-field MLSCodable type.
		var extReader = MLS.Reader(record.groupContextExtensionsProposal.bytes)
		let extensions: [MLS.RFC9420.Extension] = try extReader.decodeVector()
		try extReader.finish()
		var extWriter = MLS.Writer()
		try extWriter.encodeVector(extensions)
		#expect(Data(extWriter.bytes) == record.groupContextExtensionsProposal.bytes)

		var treeReader = MLS.Reader(record.ratchetTree.bytes)
		let nodes: [MLS.RFC9420.Node?] = try treeReader.decodeVector()
		try treeReader.finish()
		var treeWriter = MLS.Writer()
		try treeWriter.encodeVector(nodes)
		#expect(Data(treeWriter.bytes) == record.ratchetTree.bytes)
	}

	/// RFC 9420 §10: "If a client receives a KeyPackage carried within an
	/// MLSMessage object, then it MUST verify that the version field of
	/// the KeyPackage has the same value as the version field of the
	/// MLSMessage."
	///
	/// Built by re-encoding a genuine vector `key_package` with only the
	/// inner `KeyPackage.version` altered, so the outer `MLSMessage`
	/// version stays `mls10` and the two disagree exactly as the MUST
	/// describes. Everything else — including the KeyPackage's signature,
	/// which no longer covers the mutated field — is untouched, which is
	/// the point: the version disagreement must be caught at decode, not
	/// left to a later signature check that this profile does not perform
	/// at decode time.
	@Test("§10: a KeyPackage whose own version disagrees with its MLSMessage is rejected")
	func keyPackageVersionMustMatchMessage() throws {
		let record = try #require(Self.records.first)

		var reader = MLS.Reader(record.mlsKeyPackage.bytes)
		guard case .keyPackage(var keyPackage) = try MLS.RFC9420.Message(from: &reader)
		else {
			Issue.record("expected wire_format == mls_key_package")
			return
		}
		try reader.finish()
		#expect(keyPackage.version == MLS.ProtocolVersion.mls10)

		keyPackage.version = MLS.ProtocolVersion(id: 0xFFFF)
		let tampered = try MLS.RFC9420.Message.keyPackage(keyPackage).mlsEncoded()

		var tamperedReader = MLS.Reader(tampered)
		#expect(throws: MLS.RFC9420.WireError.unsupportedProtocolVersion(.init(id: 0xFFFF)))
		{
			_ = try MLS.RFC9420.Message(from: &tamperedReader)
		}
	}
}
